"""empty message

Revision ID: b76aafb1723f
Revises: 287469d7ecf7
Create Date: 2024-01-12 15:04:02.234484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b76aafb1723f'
down_revision = '287469d7ecf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breakout',
    sa.Column('break_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('break_title', sa.String(length=200), nullable=False),
    sa.Column('break_image', sa.String(length=120), nullable=True),
    sa.Column('break_status', sa.Enum('1', '0'), nullable=False),
    sa.Column('break_time', sa.DateTime(), nullable=True),
    sa.Column('break_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['break_level'], ['level.level_id'], ),
    sa.PrimaryKeyConstraint('break_id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('admin_pwd',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('admin_pwd',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    op.drop_table('breakout')
    # ### end Alembic commands ###
