"""empty message

Revision ID: ea654e1e89d2
Revises: b76aafb1723f
Create Date: 2024-01-18 12:46:33.649329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea654e1e89d2'
down_revision = 'b76aafb1723f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation',
    sa.Column('donate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('donate_amt', sa.Float(), nullable=False),
    sa.Column('donate_userid', sa.Integer(), nullable=True),
    sa.Column('donate_date', sa.DateTime(), nullable=True),
    sa.Column('donate_status', sa.Enum('pending', 'paid', 'failed'), nullable=False),
    sa.Column('donate_donor', sa.String(length=200), nullable=True),
    sa.Column('donate_email', sa.String(length=120), nullable=True),
    sa.Column('donate_ref', sa.String(length=200), nullable=True),
    sa.Column('donate_paygate', sa.String(length=200), nullable=True),
    sa.Column('donate_dateupdated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donate_userid'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('donate_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donation')
    # ### end Alembic commands ###
