"""empty message

Revision ID: eefa9bc46c39
Revises: ea654e1e89d2
Create Date: 2024-01-19 10:59:20.486604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eefa9bc46c39'
down_revision = 'ea654e1e89d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_registration',
    sa.Column('reg_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('break_id', sa.Integer(), nullable=True),
    sa.Column('datereg', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['break_id'], ['breakout.break_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('reg_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_registration')
    # ### end Alembic commands ###
